version: "3.9" # optional since v1.27.0.

# Declaraci贸n de las redes que se van a crear. 
networks:
  # Red para los contenedores (back-tier es un label).
  back-tier:
    # Nombre de la red.
    name: org_net
    # Tipo de red.
    driver: bridge
    # Gesti贸n IP.
    ipam:
      driver: default
      # Configuraci贸n de red IPv4 y puerta de enlace.
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254


# Declaraci贸n de servicios que se van a crear.
services:
  # Contenedor de persistencia en base de datos posgreSQL (postgres es un label).
  postgres:
    #image: postgres:15.0
    container_name: postgres_ctn
    # restart: "no" | always | on-failure | unless-stopped.
    restart: "no"
    build:
      # Ruta de la carpeta con el dockerfile para construir la imgen.
      context: .
      # Nombre del archivo dockerfile con las opciones de construccion de la imagen.
      dockerfile: ./dockerfiles/postgres.dockerfile
      args:
        # Para que funcione la vinculacion este es el uid/gid del host y sera el que use postgres en el contenedor.
        LOCAL_USER_ID_GID: "1000"
    #user: 1000:1000  
    environment:
      POSTGRES_DB: "tele_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/dta"
    ports:
      - "5432:5432"
    # Persistir la base de datos mas alla del ciclo de vidad del comtenedor.
    # Volumen nombrado
    volumes:
      # La primera vez db-data debe estar vacio; luego esta reemplazara a la que viene por defecto en el contenedor.
      # Para establecer los permisos adecuados, lea las recomendaciones en ./volumes/Readme.md
      - db-data:/var/lib/postgresql/data
    networks:
      back-tier:
        aliases:
          - org.organization.db-host
  # Contenedor administrador de base de datos pgAdmin4 (pgadmmin es un label)
  pgadmmin:
    container_name: pgadmin_ctn
    # restart: "no" | always | on-failure | unless-stopped
    restart: "no"
    build:
      # Ruta de la carpeta con el dockerfile para construir la imgen 
      context: .
      # Nombre del archivo dockerfile con las opciones de construccion de la imagen
      dockerfile: ./dockerfiles/pgadmin.dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: "giancarlobenavides@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "giancarlo"
      PGADMIN_SERVER_JSON_FILE: ./config/servers.json
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes: 
      - db-admin:/var/lib/pgadmin
    networks:
      back-tier:
        aliases:
          - org.organization.dbadmin-host

# Volumenes creados para el proyecto         
volumes:
  db-data: {}
  db-admin: {}
  