version: "3.9" # optional since v1.27.0

# Declaración de las redes que se van a crear   
networks:
  # Red para los contenedores (back-tier es un label)
  back-tier:
    # Nombre de la red
    name: red_org
    # Tipo de red
    driver: bridge
    # Gestión IP 
    ipam:
      driver: default
      config:
        subnet: 192.168.1.0/24
        gateway: 192.168.1.254

# Declaración de servicios que se van a crear
services:
  # Contenedor de la WEB.
  http:
    container_name: nginx_ctn
    # Opciones de restart: "no" | always | on-failure | unless-stopped
    restart: "no"
    build:
      # Ruta de la carpeta con el dockerfile de la imgen a construir
      context: ./http
      # Nombre del archivo dockerfile
      dockerfile: Dockerfile
      # argumentos docker compose
      args:
        tag-version: 11
    environment:
      POSTGRESQL_USERNAME: "giancarlo"
    ports:
      - "8000:80"
    volumes:
      - ./data_web:/var/www
    networks:
      back-tier:
        aliases:
          - nginx.host

# Archivos           
volumes:
  data_web: {}
